language = "C"
cpp_compat = true
style = "type"
include_guard = "TECTONIC_BRIDGE_CORE_GENERATED_H"
after_includes = """
typedef uintptr_t rust_input_handle_t;
typedef uintptr_t rust_output_handle_t;
#define INVALID_HANDLE ((uintptr_t)0)
"""

[enum]
prefix_with_name = true

[export.rename]
"CoreBridgeState" = "ttbc_state_t"
"Diagnostic" = "ttbc_diagnostic_t"
"FileFormat" = "ttbc_file_format"
"OutputId" = "ttbc_output_handle_t"
"InputId" = "ttbc_input_handle_t"