name: "Tectonic CI"

on:
  push:
    branches: [master, rc]
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  prep:
    uses: ./.github/workflows/prep.yml
  build_and_test:
    needs: prep
    uses: ./.github/workflows/build_and_test.yml
  deploy:
    needs: build_and_test
    if: ${{ github.event_name == 'push' }}
    uses: ./.github/workflows/deploy.yml
    with:
      is-main: ${{ github.base_ref == 'master' }}
      is-release: ${{ github.base_ref == 'rc' }}

