name: "Upload Coverage"

on:
  workflow_run:
    workflows: ["Build and Test", "PR CI", "Push CI/CD"]
    types: [completed]

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout PR"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: "Download coverage report"
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage-data
      - name: "Debug"
        run: echo "${{ toJson(github.event) }}"
      - name: "Upload coverage to codecov"
        uses: codecov/codecov-action@v5
        with:
          files: 'coverage.json'
          token: ${{ secrets.CODECOV_TOKEN }}
